
[window]
padding = { x = 10, y = 5 }
opacity = 0.6
decorations = "Full"

[font]
normal ={family = "Terminess Nerd Font", style = "Regular"}
bold = {family = "Terminess Nerd Font", style = "Bold"}
italic = {family = "Terminess Nerd Font", style = "Italic"}
bold_italic = {family = "Terminess Nerd Font", style = "Bold Italic" }
size = 11.5


[colors.primary]
background = "#0d0d0d"
bright_foreground = "#181818"

